language: go

jobs:
  include:
  - script: echo "one"
  - script: echo "two"

  - stage: deploy
    script: echo "deploy to gh releases"
    dist: bionic
    go: 1.13.x
    before_deploy:
    - sudo snap install goreleaser --classic
    - go get -u github.com/digitalocean/github-changelog-generator
    deploy:
      provider: script
      script: ./release_me.sh

  - script: echo "second deploy job"
    os: osx
    deploy:
      provider: script
      script: echo "will update brew"
